from setuptools import setup
package_name = 'mpc_solarcar'
setup(
    name=package_name,
    version='0.1.0',
    packages=[package_name],
    data_files=[
        ('share/ament_index/resource_index/packages', ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        ('share/' + package_name + '/launch', ['launch/solarcar_sim.launch.py', 'launch/passo_live.launch.py', 'launch/passo_autostart.launch.py']),
        ('share/' + package_name + '/inputs', [
            'inputs/forecast_10min.csv',
            'inputs/route_waypoints.csv',
            'inputs/stop_points.yaml',
            'inputs/drive_schedule.yaml',
            'inputs/speed_profile.csv',
            'inputs/solar_params.yaml',
            'inputs/route_profile.csv',
        ]),
        ('share/' + package_name + '/maps', [
            'maps/drive_eff_map.csv',
            'maps/regen_eff_map.csv',
            'maps/Rint_T_by_soc.csv',
            'maps/panel_eff_map.csv',
            'maps/mppt_eff_map.csv',
            'maps/drive_eff_map_eco.csv',
            'maps/drive_eff_map_power.csv',
            'maps/regen_eff_map_eco.csv',
            'maps/regen_eff_map_power.csv',
        ]),
        ('share/' + package_name + '/docs', ['docs/passo_quickstart.md', 'docs/dashboard_quickstart.md']),
        ('share/' + package_name + '/scripts', [
            'scripts/setup_can.sh',
            'scripts/can_smoke_test.sh',
            'scripts/obd_scan.py',
            'scripts/postprocess_fuel.py',
            'scripts/solar_sim.py',
            'scripts/build_motor_maps.py',
            'scripts/generate_dashboard_dummy.py',
            'passo_run.sh',
        ]),
        ('share/' + package_name + '/templates', [
            'templates/route_profile_template.csv',
            'templates/speed_profile_template.csv',
            'templates/drive_schedule_template.yaml',
            'templates/panel_eff_map_template.csv',
            'templates/mppt_eff_map_template.csv',
            'templates/drive_eff_map_template.csv',
            'templates/regen_eff_map_template.csv',
            'templates/rint_map_template.csv',
            'templates/solar_params_template.yaml',
            'templates/ocv_soc_curve_template.csv',
            'templates/battery_thermal_template.yaml',
            'templates/motor_tau_limit_template.csv',
            'templates/aux_load_profile_template.csv',
        ]),
        ('share/' + package_name + '/dashboard', [
            'dashboard/index.html',
            'dashboard/style.css',
            'dashboard/app.js',
        ]),
    ],
    install_requires=[
        'setuptools',
        'numpy',
        'scipy',
        'pandas',
        'pyyaml',
        'matplotlib',
        'python-can',
        'casadi',
    ],
    zip_safe=True,
    maintainer='you',
    maintainer_email='you@example.com',
    description='ROS2 nodes for solar car MPC with simulated GPS and a simple control panel.',
    license='MIT',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            'gps_sim_node = mpc_solarcar.gps_sim_node:main',
            'mpc_node = mpc_solarcar.mpc_node:main',
            'panel_node = mpc_solarcar.panel_node:main',
            'dashboard_node = mpc_solarcar.dashboard_node:main',
            'can_obd_node = mpc_solarcar.can_obd_node:main',
            'distance_node = mpc_solarcar.distance_node:main',
            'logger_node = mpc_solarcar.logger_node:main',
            'preflight_node = mpc_solarcar.preflight_node:main',
            'config_wizard_node = mpc_solarcar.config_wizard_node:main',
            'throttle_advisory_node = mpc_solarcar.throttle_advisory_node:main',
            'grade_node = mpc_solarcar.grade_node:main',
        ],
    },
)
